# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Setup Go environment

  uses: actions/setup-go@v4.0.1

  with:

    # The Go version to download (if necessary) and use. Supports semver spec and ranges.

    go-version: # optional

    # Path to the go.mod or go.work file.

    go-version-file: # optional

    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec

    check-latest: # optional

    # Used to pull node distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.

    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}

    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.

    cache: # optional, default is true

    # Used to specify the path to a dependency file - go.sum

    cache-dependency-path: # optional

    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.

    architecture: # optional
